// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ZinetExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ZinetExtension.b2339e4b-237c-40cc-bdc0-68050b55b5f6";
        public const string Name = "ZinetExtension";
        public const string Description = @"Extension to easy run zinet project reflection ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Paweł Krolik";
        public const string Tags = "";
    }
}
