// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ZinetExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ZinetExtensionString = "b48202b7-d82b-4ea1-bff2-ae5edfe4b534";
        public static Guid ZinetExtension = new Guid(ZinetExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int Toolbar = 0x1000;
        public const int ZinetReflectCode = 0x0101;
        public const int ZinetGenerateProject = 0x0102;
        public const int ZinetIconID = 0x0001;
    }
}